#include "pch.h"
#include "Constants.h"

Constants::Constants() {
	REGISTER_USER = "REGISTER_USER";
	LOGIN_USER = "LOGIN_USER";
	GET_ALL_USERS = "GET_ALL_USERS";
	SEND_FRIEND_REQUEST = "SEND_FRIEND_REQUEST";
	FRIEND_REQUEST = "FRIEND_REQUEST";
	PENDING = "PENDING";
	PING = "PING";
	SAVE_PROFILE_PIC = "SAVE_PROFILE_PIC";
	GET_PROFILE_PIC = "GET_PROFILE_PIC";
	FRIEND_REQUEST_ACCEPTED = "FRIEND_REQUEST_ACCEPTED";
	FRIEND_REQUEST_REJECTED = "FRIEND_REQUEST_REJECTED";
	MESSAGE = "MESSAGE";
	SEND_EVENT_REQUEST = "SEND_EVENT_REQUEST";
	GET_FRIENDS = "GET_FRIENDS";
	EVENT_REQUEST_RECEIVED = "EVENT_REQUEST_RECEIVED";
	GET_EVENT_REQUESTS = "GET_EVENT_REQUESTS";
	EVENT_REQUEST_ACCEPTED = "EVENT_REQUEST_ACCEPTED";
	GET_PENDING_EVENTS = "GET_PENDING_EVENTS";
	ACCEPTED = "ACCEPTED";
	SAVE_MEMORY = "SAVE_MEMORY";
	GET_MEMORY = "GET_MEMORY";
}